import streamlit as st
import os
import sys

# Ensure the parent directory is in sys.path so we can run this from anywhere
current_dir = os.path.dirname(os.path.abspath(__file__))
parent_dir = os.path.dirname(current_dir)
if parent_dir not in sys.path:
    sys.path.append(parent_dir)

from langchain_core.messages import HumanMessage, AIMessage
from db_analyst_agent import DBAnalystAgent

# Define the reports path dynamically (assuming it's inside db_analyst_agent)
REPORTS_DIR = os.path.join(current_dir, "reports")

# Set up page config
def render_ui():
    st.title("Database Analyst")

    # Initialize session state for chat history and agent
    if "db_messages" not in st.session_state:
        st.session_state.db_messages = []

    if "db_agent" not in st.session_state:
        st.session_state.db_agent = DBAnalystAgent()

    # Remove sidebar layout logic
    chat_container = st.container(height=550)

    with chat_container:
        # Display chat messages from history on app rerun
        for i, msg in enumerate(st.session_state.db_messages):
            with st.chat_message(msg["role"]):
                st.markdown(msg["content"])
                if "pdf_path" in msg and os.path.exists(msg["pdf_path"]):
                    import base64
                    with open(msg["pdf_path"], "rb") as f:
                        b64 = base64.b64encode(f.read()).decode()
                        href = f'<br><a href="data:application/pdf;base64,{b64}" download="{os.path.basename(msg["pdf_path"])}">*Download the k6 summary PDF*</a>'
                        st.markdown(href, unsafe_allow_html=True)

    st.markdown("---")

    # Layout for the input and buttons at the bottom
    with st.form("db_input_form", clear_on_submit=True):
        col1, col2 = st.columns([9, 1])
        with col1:
            query_input = st.text_input("Ask a query or enter run_id", label_visibility="collapsed", placeholder="Ask a query or enter run_id...")
        with col2:
            send_btn = st.form_submit_button("Send", use_container_width=True)

    if send_btn and query_input:
        st.session_state.db_messages.append({"role": "user", "content": query_input})
        
        langchain_messages = []
        for m in st.session_state.db_messages[:-1]:
            if m["role"] == "user":
                langchain_messages.append(HumanMessage(content=m["content"]))
            else:
                langchain_messages.append(AIMessage(content=m["content"]))
                
        last_content = query_input
        is_pdf_request = any(keyword in last_content.lower() for keyword in ["pdf", "report"]) and "generate" in last_content.lower()
        if is_pdf_request:
            last_content += " (Instruction: Call the generate_pdf_report tool. Do NOT output any textual summary or paragraphs describing the metrics. Only output a brief confirmation that the PDF has been generated.)"
        langchain_messages.append(HumanMessage(content=last_content))
                
        with st.spinner("Thinking..."):
            try:
                state = {"messages": langchain_messages}
                response = st.session_state.db_agent.invoke(state)
                ans = response["messages"][0].content
                
                # Check if a PDF was generated by looking at intermediate steps
                pdf_path = None
                for action, observation in response.get("intermediate_steps", []):
                    if action.tool == "generate_pdf_report":
                        if "at: " in str(observation):
                            pdf_path = str(observation).split("at: ")[1].strip()
                
                msg_obj = {"role": "assistant", "content": ans}
                if pdf_path:
                    msg_obj["pdf_path"] = pdf_path
                    
                st.session_state.db_messages.append(msg_obj)
            except Exception as e:
                error_msg = f"Error: {e}"
                st.session_state.db_messages.append({"role": "assistant", "content": error_msg})
                
        st.rerun()


if __name__ == "__main__":
    st.set_page_config(page_title="DB Analyst", layout="wide")
    render_ui()